#!/bin/bash

INCLUDES="-I/home/adam/system/src/libPanicLog"
LIBS="-L/home/adam/system/lib -lm -lPanicLog -lpthread"

gcc -ansi -rdynamic -Wall -Wpedantic -g3 $INCLUDES -c -o particle.o \
	particle.c &&
gcc -ansi -rdynamic -Wall -Wpedantic -g3 $INCLUDES -c -o simulator.o \
	simulator.c &&
gcc -ansi -rdynamic -Wall -Wpedantic -g3 $INCLUDES -c -o data.o \
	data.c &&
gcc -rdynamic -Wall -Wpedantic -g3 $LIBS -o simulator particle.o \
	simulator.o data.o &&
(echo "Success" && exit 0) ||
(echo -e '\aError!' && exit 1)
