#!/bin/bash

# Number of MPI processes to run
MPI_PROCESSES=4

# Number of particles in the simulation
NUM_PARTICLES=200

# The size of the initial volume in which particles are spawned
VOLUME_SIZE=2000.0

# What's the maximum multiple one particle's mass can be from another
MASS_RANGE=1000

# Line length
LINE_LENGTH=250

# Initial velocity of particles (NOTE: they have random direction)
VELOCITY=2.5

# The number of particles to track
# Normally you'd want this to be the number of particles, or one or two
LINE_FOLLOW=$NUM_PARTICLES

# The universal constant G
GRAVITY=0.25

# Threshold for acceleration warnings
THRESHOLD=10.0

# Radius
RADIUS=4000.0

mpicc -O3 -lm -DFX -DXMESA -lGL -lGLU -lglut -lX11 -o nbody_mpi nbody_mpi.c &&
#LD_PRELOAD=/usr/lib64/valgrind/libmpiwrap-amd64-linux.so mpirun --bind-to-core --report-bindings -n $MPI_PROCESSES valgrind --log-file="valgrind-%p.log" ./nbody_mpi --particles=$NUM_PARTICLES --volume=$VOLUME_SIZE --mass=$MASS_RANGE --lines=$LINE_LENGTH --velocity=$VELOCITY --follow=$LINE_FOLLOW --gravity=$GRAVITY --threshold=$THRESHOLD --radius=$RADIUS
mpirun --bind-to-core --report-bindings -n $MPI_PROCESSES ./nbody_mpi --particles=$NUM_PARTICLES --volume=$VOLUME_SIZE --mass=$MASS_RANGE --lines=$LINE_LENGTH --velocity=$VELOCITY --follow=$LINE_FOLLOW --gravity=$GRAVITY --threshold=$THRESHOLD --radius=$RADIUS --colour=8 &&
exit 0 ||
exit 1
