#!/bin/bash
#
# Same as `simpleci` but for C++ source files

if [ $# -ne 1 ]; then
	echo 'Wrong number of arguments!!' > /dev/stderr
	
	exit 1
fi

if [ -z "$CPPFLAGS" ]; then
	CPPFLAGS="-g3 -Wall -Wno-write-strings"
fi

g++ $CPPFLAGS -xc++ -o "$@" -

exit $?
